---
name: "release"

on:
  push:
    tags:
      - v*

env:
  TARGET_NAME: vecx

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install
        run: make install
      - name: Build
        run: type=all version=${GITHUB_REF##*/} make build
      - name: Zip
        run: zip -j ${{ env.TARGET_NAME }}-linux-x86_64.zip target/x86_64-unknown-linux-gnu/release/${{ env.TARGET_NAME }}
      - name: Zip
        run: zip -j ${{ env.TARGET_NAME }}-windows-x86_64.zip target/x86_64-pc-windows-gnu/release/${{ env.TARGET_NAME }}.exe
      - name: Shasum
        run: |
          shasum -a 256 ${{ env.TARGET_NAME }}-linux-x86_64.zip > ${{ env.TARGET_NAME }}-linux-x86_64.zip.sha256
          shasum -a 256 ${{ env.TARGET_NAME }}-windows-x86_64.zip > ${{ env.TARGET_NAME }}-windows-x86_64.zip.sha256
      - name: Upload
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.AI_FLOWX_TOKEN }}
        with:
          asset_paths: '["${{ env.TARGET_NAME }}-linux-x86_64.zip", "${{ env.TARGET_NAME }}-linux-x86_64.zip.sha256", "${{ env.TARGET_NAME }}-windows-x86_64.zip", "${{ env.TARGET_NAME }}-windows-x86_64.zip.sha256"]'

  crates:
    runs-on: ubuntu-latest
    needs: [linux_windows]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
